namespace BloodDonation.Constants;

public static class Districts
{
    public static List<string> Value = new()
    {
        "Jhapa",
        "Ilam",
        "Panchthar",
        "Taplejung",
        "Morang",
        "Dhankuta",
        "Tehrathum",
        "Sankhuwasabha",
        "Bhojpur",
        "Solukhumbu",
        "Okhaldhunga",
        "Sunsari",
        "Khotang",
        "Udayapur",
        "Saptari",
        "Siraha",
        "dhanusha",
        "Mahottari",
        "Sarlahi",
        "Rautahat",
        "Bara",
        "Parsa",
        "Sindhuli",
        "Ramechhap",
        "Dolakha",
        "Sindhupalchowk",
        "Kavrepalanchowk",
        "Lalitpur",
        "Bhaktapur",
        "Kathmandu",
        "Nuwakot",
        "Rasuwa",
        "Dhading",
        "Makawanpur",
        "Chitwan",
        "Gorkha",
        "Lamjung",
        "Tanahu",
        "syangja",
        "Kaski",
        "Manang",
        "Mustang",
        "Myagdi",
        "Parbat",
        "Baglung",
        "Nawalparasi (Purba)",
        "Gulmi",
        "Palpa",
        "Rupandehi",
        "Kapilvastu",
        "Arghakhanchi",
        "Pyuthan",
        "Rolpa",
        "Dang",
        "Banke",
        "Bardiya",
        "Nawalparasi (Paschim)",
        "Rukum (Purbha)",
        "Salyan",
        "Surkhet",
        "Dailekh",
        "Jajarkot",
        "Dolpa",
        "Jumla",
        "Kalikot",
        "Mugu",
        "Humla",
        "Rukum (Pashim)",
        "Bajura",
        "Bajhang",
        "Achham",
        "Doti",
        "Kailali",
        "Kanchanpur",
        "Dadheldhura",
        "Baitadi",
        "Darchula",
    };
}